### ISSUE TITLE
Please update to new version

### ISSUE THREAD

**Issue by serkandurusoy** [Nemo64/meteor-bootstrap-data#2]
This version of bootstrap is 4 months old and there are numerous enhancements / fixes as of January 19.

Thanks.

**Comment by guaka** [comment]
+1

**Comment by tgoorden** [comment]
+1

**Comment by krishprasadar** [comment]
+1

**Comment by serkandurusoy** [comment]
Ping! bootstrap@3.3.4 is now released

**Comment by vichoiglesias** [comment]
+1

**Comment by emgee3** [comment]
Hey all, I've updated to 3.3.4 this morning.
